### ISSUE TITLE
Incorporating Map Editor

### ISSUE THREAD

**Issue by HunterNN** [Codename-Recon/Codename-Recon#10]
Currently, to create a map, one has to place nodes directly into the scene. This process should be enhanced by implementing the use of Godot's tiled map editor. The new system should have the capability to automatically choose the correct tile based on the neighboring tiles, while still retaining all the information that a tile needs to provide.

### Todos
- [x] **Tile Map auto tiling**
- [x] **Tile Map to Map**: Map generation while using tile map (visible game map and hidden tile map autotile logic)
- [ ] **Map to Tile Map**: Allow existing maps to be edited, generating the corresponding tile map for editing tiles with autotiling
- [x] **Map to JSON**: Enable saving a map state as JSON to a file (and in the future send it to the server for synchronization)
- [x] **JSON to Map**: Implement loading a map file (and receiving one from the server in the future)

I spoke with Ephraim225, who provided some good suggestions for the map editor that should be implemented:
- [ ] Implement the ability to set statis for units (e.g. health, river flow direction, AI behavior)
- [ ] Add regional copy-and-paste functionality based on <https://github.com/joaofrancese/awsmaped>
- [ ] Incorporate line, circle, and square tools based on <https://github.com/joaofrancese/awsmaped>
- [ ] Provide the option to place individual tiles without automatic tiling
- [ ] Add a setting for roads to connect to buildings while placing tiles

**Comment by Dracks** [comment]
Your idea is to use the autotilemapper from godot? 
https://www.youtube.com/watch?v=vV8uKN1VnN4

**Comment by HunterNN** [comment]
Yes, but I think we need to test if this is a good solution. For instance, is it possible to use it in the game so that we can implement an editor inside of it? Does it work with the custom node Terrain, which I created, or are these more similar to Sprites/Textures with certain properties?

**Comment by HunterNN** [comment]
I have revised the issue text based on the new information provided.
